### PR TITLE
Fire VerificationEmailSent Event

### PR DESCRIPTION
**Pull request by lukasoppermann**
This PR adds an event that is fire once the verification email is sent.

This can be very useful for example when you want to log the fact that the email was sent. Or if you want to store a timestamp so that you can wait for x minutes until you remind the user again, to verify the email...

### CODE REVIEW

**Comment by jrean** [comment]
Hi, I like this contribution. Thank you.
Can you please make sure it is compliant with the branch 2.2 (laravel 5.[0.1.2]).
Every time you send a PR over master I need to check if it is ok with branch 3.0 (Laravel 5.3) but also with branch 2.2.

I will review it tomorrow

**Comment by lukasoppermann** [comment]
As far as I understand from the laravel docs, it should be. However this would be a good case for tests, as you could easily run them for all environments via travis for every PR.

**Comment by lukasoppermann** [comment]
Will you merge this or should I rebase?

**Comment by jrean** [comment]
Yes of course, I will merge it. I need to review it first :-)
It's a great addition.

**Comment by lukasoppermann** [comment]
Okay, just did a rebase, so it should now work with the current master

**Comment by jrean** [comment]
Thank you.

**Pull request merged**
