### PR TITLE
Implement confirmation expiration

### PR DESCRIPTION
**Pull request by Konafets**
The current version does not support tokens which can expire. This could be archived by adding a new field `expire_date` to the `users` table, but would pollute the table with an extra _one-time-use_ field as the `confirmation_token` already is.

Therefore lets create a new table which handles the confirmation tokens and the expiration date.

### CODE REVIEW

**Comment by Konafets** [comment]
The idea with an middleware does not work out. I will include it in the code and make it configurable through the config.

**Comment by mohamedsabil83** [comment]
Thank you for this feature I planned to do it but nice you do it.

N.B.: In **resendConfirmationMail** function, the message in following line need to be localization:
```php
return redirect()->route('login')->withSuccess('Bitte prüfen Sie Ihren E-Mail Posteingang.');
```

**Comment by k-zafar** [comment]
If this works fine then @jrean please merge this code.

Thanks!

**Comment by Konafets** [comment]
@jrean What is the status here? Do you consider to merge this?

**Comment by mirko77** [comment]
@Konafets would this work on Laravel 5.4, v4.1 of the package?

**Comment by Konafets** [comment]
@mirko77 I used this with Laravel 5.6 and the `dev-develop` version of this package.

**Pull request closed without merging**
