### PR TITLE
Replace try and catch by using exception handler

### PR DESCRIPTION
**Pull request by fen9li**
Change details 

1/ Removing try-catch block in 'public function getVerification(Request $request, $token)' /  ‘vendor/jrean/laravel-user-verification/src/Traits/VerifiesUsers.php’

2/ Cleaning up ‘vendor/jrean/laravel-user-verification/src/Traits/RedirectsUsers.php’ 
3/ Updating ‘app/Exceptions/Handler.php’ 
4/ Creating error view

### CODE REVIEW

**Comment by jrean** [comment]
@fen9li thank you for your contribution.

> 1/ Removing try-catch block in 'public function getVerification(Request $request, $token)'

Why? Can you please explain?

> 2/ Cleaning up ‘vendor/jrean/laravel-user-verification/src/Traits/RedirectsUsers.php’ 

Why do you want to remove `redirectIfVerified()`?

> 3/ Updating ‘app/Exceptions/Handler.php’ 

I don't see anything related to this into your PR

> 4/ Creating error view

Please refer to https://github.com/jrean/laravel-user-verification/releases/tag/v3.0.3
It has been implemented today

**Comment by fen9li** [comment]
@jrean  Thank you for your effort.. this is a great package for Laravel 5.3 actually.

There is nothing wrong with current implementation ... 
However, I prefer using Exceptions... more readable, easier to maintain ...
And as you can see, more lines replaced with less ...

**Comment by fake-fur** [comment]
@fen9li having explicit exceptions for user stuff is a terrible idea from a security perspective - please do not use this patch and leave it as a generic error

**Comment by jrean** [comment]
Agree.
But by default the package throws a `UserNotFoundException` if no user is found for the given e-mail. I implemented try / catch and then I redirect to the error view. I reckon it gives the flexibility to end users for implementation + allow anyway to override the `getVerification()` for custom behaviour.

What do you think @fake-fur ?

I'm sorry @fen9li but, I don't think I will merge nor implement this PR like that right now.
I'm working on the `3.1` release. All ideas and suggestions are welcome

**Comment by fake-fur** [comment]
i agree - the package is really easy to integrate into laravel even for a complete laravel beginner like me

**Pull request closed without merging**
