### PR TITLE
Provide resend route

### PR DESCRIPTION
**Pull request by lukasoppermann**
Hey @jrean,

this PR for #51 is not completely done yet, but maybe you can already test it in any case.
### Concerns / todos:
- b/c break for people who rely on the routes from the package to the RegisterController
- Controller needs to be publishable & overwritable to customize things like `redirectIfVerified` (publish not implemented, overwrite not tested yet)
  - this should be moved to a config file though
### Discussion
- Are you fine with doing a `redirect back();` which might include an `error` flash message? Should we namespace the flash message? Like `user-verification-error`.
- I implemented it using a `post` with a `user_id` which makes sense for me, as it is a kind of `post` action and this allows us to use the resend route also for e.g. for an admin resending a link to a user by triggering a post request with another users user_id

### CODE REVIEW

**Comment by lukasoppermann** [comment]
@jrean changed. Makes sense. Anyway those are the options we should probably move to a config file later on.

**Comment by lukasoppermann** [comment]
@jrean am I correct on thinking that we can remove this part once the controller is merged.

```php
   /**
        * Create a new controller instance.
        *
        * @return void
        */
        public function __construct()
        {
            // Based on the workflow you need, you may update and customize the following lines.

            $this->middleware('guest', ['except' => ['getVerification', 'getVerificationError']]);
        }

```

**Comment by lukasoppermann** [comment]
Hey @jrean did you get a chance to test this? Do you need any change or could this me merged? May it would be better to actually to a `minor` semver increase as this adds functionality. So using a `minor` version bump would be correct: http://semver.org/

**Comment by jrean** [comment]
I will review this one tomorrow as it concerns a "major" change and will be tagged as part of the 3.1 version

**Comment by jrean** [comment]
Luka, I'm reviewing the code. I need more time before merging.
I need to discuss with you the "Resend" functionality you implemented.
The flow of this package is (to me)

- 1) User Registers (user may be logged in or not after that step)
- 2) Verification token is generated and stored
- 3) Verification token is sent by e-mail
- 4) Token (user) is verified
- 5) User is set as verified

The correct question is WHEN a "re-send" option may be needed.
- Number 3) fails. Something went wrong. An error page may be displayed and offers a button to re-launch the process. But how? If the user is logged in, easy. But what if the user is not logged in (part of an app specifications)? User should be asked to provide his e-mail address and some checks should be performed (or not) ... What is the user enters an e-mail which is not his e-mail or which is not registered...

- Number 4) fails. Same as number 3)

- An admin wants manually to re-launch the process of verification for 1 or many users...

Hence why (I remember now) why I didn't implement this functionality into the past releases. To me it is not part of the package but should be implemented by the end users of this package. This package was designed to provide the shell of a user verification.

I really need to think twice about this (again).

So far, I agree with you by creating a Controller and extracting everything into it.
I working on it now.

Into the controller you provided:

You added at the top

```
use Jrean\UserVerification\Traits\RedirectsUsers;
```

But you didn't include the `use` statement it into the `class` itself.
Is it a mistake?

Please share you thoughts again.

**Comment by lukasoppermann** [comment]
Hey @jrean,

> But you didn't include the use statement into the class itself.
> Is it a mistake?

Indeed, I added it when you asked me to move the methods back to the trait and forgot the use statement. (Fixed now).

Apart from this: 

I think the most important case is actually a user not receiving the email (spam, etc.) or accidentally deleting/archiving the email. Both from projects and also my experience as a user, I know that verification emails are often requested again by users due to those cases. 

I think the case is actually quite common, so that I think it belongs in this package, as it does no depend on your specific project. Nearly every website with verification offers a simple `resend` functionality and they are all the same: click link -> get email. 😄 

For other cases, e.g. admin resending, errors, etc. I agree that this might not be needed in the package itself.

However, a user requesting a new verification email is pretty standard and should be included.

**Comment by jrean** [comment]
Thanks. I agree with you.
So, now, regarding the implementation.
- What if the user is logged
- What is the user is not logged

These are two main differents case scenarios. For the first one, we have access to the user and we can retrieve the e-mail address. For the last one, we don't have any details. We need to take that into account. I know by experience that sometimes application doesn't allow a user to login until he/she verifies its e-mail...

Let's brainstorm a little bit. What do you think?

**Comment by lukasoppermann** [comment]
We probably should allow both cases.

Personally I would prefer my users to not be able to login before they are verified, but this is not always the case.

The question is, can we may trigger the resend with just an email address instead of a whole user object? This way it would not matter if a user is logged in or not, as long as the email is provided.

**Comment by lukasoppermann** [comment]
@jrean what do you think about this?

> The question is, can we maybe trigger the resend with just an email address instead of a whole user object? This way it would not matter if a user is logged in or not, as long as the email is provided.

**Comment by Konafets** [comment]
Any progress on this topic?

**Comment by jrean** [comment]
@Konafets,
Still working on it. @lukasoppermann proposed something really interesting.

Until it's part of the core package and as mentioned at the end of the documentation you can easily implement this step:

If you want to regenerate and resend the verification token, you can do this with the following two lines:

```
UserVerification::generate($user);
UserVerification::send($user, 'My Custom E-mail Subject');
```

The generate method will generate a new token for the given user and change the verified column to 0. The send method will send a new e-mail to the user.

**Comment by lukasoppermann** [comment]
Just FYI, I am not doing anything here. @jrean Feel free to take this over if you are ready to merge.

**Pull request closed without merging**
